<?php

// Array untuk menyimpan daftar bidang ilmu
$bidang_ilmu = [
    "REKAYASA TEKNOLOGI INFORMASI",
    "REKAYASA KEAMANAN SIBER",
    "KEAMANAN SISTEM INFORMASI KEIMIGRASIAN",
    "ADMINISTRASI SISTEM INFORMASI TEKNOLOGI",
    "ADMINISTRASI INFORMASI KOMPUTER",
    "APLIKASI PERANGKAT LUNAK SITUS",
    "DUKUNGAN TEKNIS TEKNOLOGI INFORMASI",
    "ILMU KOMPUTER ATAU INFORMATIKA",
    "KEAMANAN SISTEM INFORMASI",
    "PENGEMBANGAN APILKASI BERGERAK",
    "PENGEMBANGAN PERANGKAT LUNAK SITUS",
    "KECERDASAN BUATAN",
    "REKAYASA SISTEM KOMPUTER",
    "LAYANAN INTERNET",
    "KECERDASAN BUATAN DAN ROBOTIK",
    "MANAJEMEN BASIS DATA",
    "PENGEMBANGAN APLIKASI MULTIPLATFORM",
    "SISTEM DAN TEKNOLOGI INFORMASI",
    "SISTEM INFORMASI",
    "PERANCANGAN PERMAINAN",
    "SISTEM INFORMASI INDUSTRI OTOMOTIF",
    "SISTEM INFORMASI KOTA CERDAS",
    "REKAYASA PERANGKAT LUNAK",
    "TEKNIK PENGAMANAN SIBER",
    "TEKNOLOGI INFORMASI",
    "REKAYASA PERANGKAT LUNAK APLIKASI",
    "TEKNOLOGI KOMPUTER GRAFIS",
    "TEKNOLOGI PERMAINAN",
    "TEKNOLOGI REKAYASA KOMPUTER GRAFIS",
    "TEKNOLOGI REKAYASA MULTIMEDIA",
    "TEKNOLOGI REKAYASA MULTIMEDIA GRAFIS",
    "TRANSAKSI PEMBAYARAN MEDIS ELEKTRONIK",
    "TEKNOLOGI REKAYASA PERANGKAT LUNAK",
    "LOGIKA",
    "MATEMATIKA TERAPAN",
    "ASURANSI KESEHATAN",
    "ASURANSI JIWA",
    "ASURANSI KERUGIAN",
    "STATISTIKA TERAPAN",
    "ILMU ATAU SAINS AKTUARIA",
    "MATEMATIKA",
    "STATISTIKA BISNIS",
    "STATISTIKA"
];

// Mengonversi array ke format JSON
$json_data = json_encode($bidang_ilmu, JSON_PRETTY_PRINT);

// Menyimpan JSON ke file
file_put_contents('bidang_ilmu.json', $json_data);

echo "Data berhasil disimpan ke file bidang_ilmu.json";

?>